first_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.shortcuts import redirect, reverse
from rango import views
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/register_profile/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
#    url(r'^register/$', views.register, name='register'),
#    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
#    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page'),
]

rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.validators import MinValueValidator

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField(max_length=200)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):

    user  = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter page title.")
    url = forms.URLField(max_length=200, help_text="PLease enter page URL.")
    views = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Page
        exclude = ('category', )

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):

    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

rango/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Category
from rango.models import Page
from rango.models import UserProfile, User
from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm
from datetime import datetime as dt
from rango.bing_search import run_query

#helper function to visitor_cookie_handler
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)

    if not val:
        val = default_val
    return val

# ------All the commented out part was of getting 
# page visits using cookies --------
#def visitor_cookie_handler(request, response):

def visitor_cookie_handler(request):

    #visits = int(request.COOKIES.get('visits', '1'))
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    
    #ast_visit_cookie = request.COOKIES.get('last_visit', str(dt.now()))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(dt.now()))

    last_visit_time = dt.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (dt.now() - last_visit_time).seconds > 0:
        visits = visits + 1

        request.session['last_visit'] = str(dt.now())
        #response.set_cookie('last_visit', str(dt.now()))
        
    else:
        visits = 1

        request.session['last_visit'] = last_visit_cookie
        #response.set_cookie('last_visit', last_visit_cookie)
        
    #response.set_cookie('visits', visits)
    request.session['visits'] = visits

def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {'categories': category_list,
                    'pages': page_list,
                     #request.COOKIES.get('visits', visitor_cookie_handler)
                    }

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    
    response = render(request, 'rango/index.html', context_dict)
    #visitor_cookie_handler(request, response)
    
    return response

def about(request):
    request.session.set_test_cookie()

    visitor_cookie_handler(request)
  
    return render(request, 'rango/about.html', {'visits':request.session['visits']})

def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        category.views = category.views + 1

        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages
        context_dict['category'] = category
        context_dict['views'] = category.views
        
        category.save()
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    print("Show category wali: ",request)
    #search func
    context_dict['result_list'] = None
    context_dict['query'] = None
    if request.method == 'POST':
        query = request.POST.get('query')
        print(query)
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)
            context_dict['result_list'] = result_list
            context_dict['query'] = query

    if not context_dict['query']:
        context_dict['query'] = category.name

    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
            
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def like_category(request):
    print("Like category wali: ",request)
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        print("CAT_ID:",cat_id)
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
    return HttpResponse(likes)

#helper function to suggest_category()
def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list

def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)

    return render(request, 'rango/cats.html', {'cats': cat_list})

@login_required
def add_page(request, category_name_slug):
    print("Add page wali: ",request)
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    
    return render(request, 'rango/add_page.html', {'form': form, 'category': category})

@login_required
def auto_add_page(request):
    cat_id = None
    url = None
    title = None
    context_dict ={}

    print("Auto add page wali: ",request)
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(category=category, title=title, url=url)
            pages  = Page.objects.filter(category=category).order_by('-views')
            context_dict['pages'] = pages

    return render(request, 'rango/page_list.html', context_dict)

def track_url(request):
    pid=None
    if request.method == 'GET':
        if 'page_id' in request.GET:
            pid = request.GET['page_id']
            print(pid)

            page = Page.objects.get(id=pid)
            page.views = page.views + 1
            page.save()
        
            return redirect(page.url)
        else:
            return redirect('/rango/')

def search(request):
    result_list = []
    query = ""
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list, 'query':query})

'''
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form =UserProfileForm()

    return render(request, 'rango/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            #print("Invalid login details: {0}, {1}".format(username, password))
            return render(request, 'rango/login.html', {'msg':"Invalid login credentials. Please try again."})
    else:
        return render(request, 'rango/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))
'''

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect('/rango/')
        else:
            print(form.errors)

    context_dict = {'form':form}

    return render(request, 'rango/profile_registration.html', context_dict)

@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('/rango/')

    userprof = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprof.website, 'picture': userprof.picture})
    
    if request.method == "POST":

templates/rango/about.html
<!DOCTYPE HTML>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    This about page is created by Dhruv Desai just for sake of "about" section. 
    <a href="/rango/">Home</a><br />
    <p>You visited Home page {{ visits }} times today.</p>

    <button class="btn btn-primary" id="about-btn">
        Click Me - I'm JavaScript on Speed
    </button>
    <p>This is a example</p>
    <p>This text is for JQuery Example</p>

    <div id="msg">Hello - I'm here for a JQuery Example too</div>

    <img class="hehe" src="{% static "images/naruto.png" %}" alt="Seventh Hokage" height="600px" width="800px"/> 

{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Adding Category
{% endblock %}

{% block body_block %}
<h2 class="form-signin-heading">Add a Category</h2>
    <div>
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
            {% endfor %}
            <br/>
            <button type="submit" name="submit" class="btn btn-primary"> Add Category </button>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Adding Page
{% endblock %}

{% block body_block %}
    <h2 class="form-signin-heading">
        Add a Page to
        <a href="/rango/category/{{category.slug}}/">{{ category.name }}</a>
    </h2>
        {% if category %}
            <form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
                {% csrf_token %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
                {% endfor %}
                <br/>
                <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
            </form>
        {% else %}
            <p>This is category does not exist.</p> {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<script src = "{% static "js/jquery.min.js" %}"></script>
<script src = "{% static "js/rango-jquery.js" %}"></script>
<script src="{% static "js/rango-ajax.js" %}"></script>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title> Rango - 
        {% block title %} 
            How to Tango with Django!
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

</head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <h3><a style="color:greenyellow" class="navbar-brand" href="#">Rango</a></h3>
        <div id="navbar">
            <nav class="nav navbar-nav pull-xs-left">
            <a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
          <!--  <a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a> -->
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
            <a class="nav-item nav-link" href="{% url 'rango:profile' user.username %}">Your Profile</a>
            <a class="nav-item nav-link" href="{% url 'rango:add_category' %}"> Add a New Category</a>
            <a class="nav-item nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'registration_register' %}">Register Here</a>
            <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
            {% endif %}
            </nav>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-list flex-column">
                <li class="nav-header">Type to find a category</li>
                <form>
                    <li><input class="search-query form-control" type="text"
                            name="suggestion" value="" id="suggestion" />
                    </li>
                </form>
            </ul>
            <hr>
            <div id="cats">
            </div>                
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block body_block %} {% endblock %}
        </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
    </script>
    <script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
    </script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script
        src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
    </script>
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}
{% load bootstrap_toolkit %}

{% block title_block %}
    {{ categorgy.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>  <p>Views:{{ views }}</p>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people likes this category
            {% if user.is_authenticated %}

                <button id="likes" data-catid="{{category.id}}"
                    class="btn btn-primary btn-sm" type="button">
                    Like
                </button>
            {% endif %}
        </div>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                <label style="color:rgb(150, 148, 148); font-size:12px ">Page Views: {{ page.views }}</label>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
    {% else %}
        The specified category does not exist!
    {% endif %}
    
        <!--- Search form for searching inside rango categories -->
    <div>
        {% if user.is_authenticated %}
        <hr />
        <label>Search other external pages if you want to.</label>
            <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}" >
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" size="100" name="query" value="{{ query }}" id="query" />
                    </div>
                    <button class="btn btn-primary" types="submit" name="submit" value="Search">Search</button>
                </form>
                <div>
                    {% if result_list %}
                        <h3>Results</h3>
                        <!-- Display search results in an ordered list -->
                        <div class="list-group">
                        {% for result in result_list %}
                            <div class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <a href="{{ result.link }}">{{ result.title }}</a>
                                </h4>
                                <p class="list-group-item-text">{{ result.summary }}</p>
                                <button data-catid="{{category.id}}" data-title="{{ result.title }}"
                                        data-url="{{ result.link }}" 
                                        class="rango-add btn btn-info btn-sm" type="button">
                                    Add
                                </button>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
        {% endif %}
    </div>
{% endblock %}

templates/rango/cats.html
<!DOCTYPE html>

<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li> <strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            <h3>Howdy {{ user.username }}!</h3>
        {% else %}
            <p>You visited Home page {{ visits }} times today.</p>
            <h2>Hey there partner!</h2>
        {% endif %}
</div>
<div class="row_marketing">
    <div class-"col-lg-6">
        {% if categories %}
            <h4>Most Liked Categories</h4>
            <p>
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item">
                    <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                    &nbsp;
                    <span class="badge badge-pill badge-primary">{{ category.views }}</span>
                </li>
                {% endfor %}
           </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
    <div class="col-lg-6">
        {% if pages %}
            <h4>Most Viewed Pages</h4>
            <p>
            <ul class="list-group">
                {% for page in pages %}
                <li class="list-group-item">
                    <a href="{{ page.url }}">{{ page.title }}
                        &nbsp;
                        <span class="badge badge-pill badge-primary">{{ page.views }}</span>
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
        </p>
    </div>
</div>
{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}
    User Profiles
{% endblock %}

{% block body_block %}
    <h1>User Profiles</h1>
    <div class="panel">
        {% if userprofile_list %}
        <div class="panel-heading">
            <!-- Display search results in an ordered list -->
            <div class="panel-body">
                <div class="list-group">
                    {% for listuser in userprofile_list %}
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">
                                <a href="{% url 'rango:profile' listuser.username %}">{{ listuser.username }}</a>
                            </h4>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% else %}
            <p>There are no users for the site.</p>
        {% endif %}
    </div>
{% endblock %}

templates/rango/page_list.html
{% if pages %}
    <ul>
    {% for page in pages %}
        <li>
            <a href="{% url 'rango:goto' %}?page_id={{page.id}}"\>{{ page.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <strong>No pages currently in category.</strong>
{% endif %}

templates/rango/profile_registration.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Registration - Step 2
{% endblock %}


{% block body_block %}
    <h1>Registration - Step 2</h1>
    <form method="post" action="." enctype="multipart/form-data">
    <!---
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Submit">
    -->    
        <!-- Website -->
        <label>User Website URL(if you have one)</label>
        
        <input type="url" name="website" id="id_website" class ="form-control">
        <!-- Picture -->

        <label>Upload user profile picture</label>
        <input type="file" name="picture" id="id_picture" class ="form-control">

        <button class="btn btn-primary" type="submit" value="Submit" />Set Up Profile</button>
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
        
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <br />
    <p>Just a simple page which is restricted to non users.
        Just for the sake of example. This page extends the <b>base.html</b>
    </p>
{% endblock %}

templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}
    Search
{% endblock %}

{% block body_block %}
<div>
 <!--   <h1>Search with Rango</h1><br/> -->
    <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}" >
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="100" name="query" value="{{ query }}" id="query" />
        </div>
        <button class="btn btn-primary" types="submit" name="submit" value="Search">Search</button>
    </form>
    <div>
        {% if result_list %}
            <h3>Results</h3>
            <!-- Display search results in an ordered list -->
            <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="{{ result.link }}">{{ result.title }}</a>
                    </h4>
                    <p class="list-group-item-text">{{ result.summary }}</p>
                </div>
            {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}